on:
    - push
    - pull_request
    - release
    - workflow_call

jobs:
    create_website:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v5
            with:
                submodules: 'recurisve'
          - run: |
                python scripts/compile_website.py
            shell: bash
          - uses: actions/upload-pages-artifact@v4
            with:
                path: build/website/

    deploy_website:
        runs-on: ubuntu-latest
        needs: create_website
        environment:
            name: github-pages
            url: www.randallscharpf.com
        permissions:
            pages: write
            id-token: write
        steps:
          - uses: actions/deploy-pages@v4
            continue-on-error: true
