on:
    - push
    - pull_request
    - release
    - workflow_call

jobs:
    create_website:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v5
            with:
                submodules: 'recurisve'
          - run: |
                python scripts/compile_website.py
            shell: bash
          - uses: actions/configure-pages@v5
          - uses: actions/upload-pages-artifact@v4
            with:
                path: build/website/

    deploy_website:
        runs-on: ubuntu-latest
        needs: create_website
        if: github.ref == 'refs/heads/main'
        environment:
            name: github-pages
            url: https://www.randallscharpf.com
        permissions:
            pages: write
            id-token: write
        steps:
          - uses: actions/deploy-pages@v4

    verify_website:
        strategy:
            matrix:
                url:
                  - "http://randallscharpf.com"
                  - "https://randallscharpf.com"
                  - "http://www.randallscharpf.com"
                  - "https://www.randallscharpf.com"
        runs-on: ubuntu-latest
        needs: deploy_website
        steps:
          - uses: actions/download-artifact@v7
            with:
                name: github-pages
          - run: |
                ls -R
                wget ${{matrix.url}} 2>wget.log
                ls -R
                grep ':443' wget.log
                diff github-pages/index.html index.html
